var activity = [
    {
        "id": 1,
        "activity":"Child Support",
        "image": "childSupport.png",
        "color": "#FFBD3E",
    },
    {
        "id": 2,
        "activity":"Refuge shelter",
        "image": "refuseShelter.png",
        "color": "#FF7044",
    },
    {
        "id": 3,
        "activity":"Food Charity",
        "image": "foodCharity.png",
        "color": "#3F90FC",
    },
    {
        "id": 4,
        "activity":"Host a clothing swap",
        "image": "clothSwap.png",
        "color": "#421FCF",
    },
    {
        "id": 5,
        "activity":"Host a river clean-up",
        "image": "riverClean.png",
        "color": "#3F90FC",
    },
    {
        "id": 6,
        "activity":"Clean water for children",
        "image": "cleanWater.png",
        "color": "#421FCF",
    },
    {
        "id": 7,
        "activity":"Good education",
        "image": "goodEducation.png",
        "color": "#FFBD3E",
    },
    {
        "id": 8,
        "activity":"New book for children",
        "image": "newBooks.png",
        "color": "#FF7044",
    },
    {
        "id": 9,
        "activity":"Host a study group.",
        "image": "studyGroup.png",
        "color": "#FFBD3E",
    },
    {
        "id": 10,
        "activity":"Build birdhouses for your neighbours.",
        "image": "birdHouse.png",
        "color": "#3F90FC",
    },
    {
        "id": 11,
        "activity":"Organize books at the library",
        "image": "libraryBooks.png",
        "color": "#FF7044",
    },
    {
        "id": 12,
        "activity":"Give a seminar on driving safety",
        "image": "driveSafety.png",
        "color": "#421FCF",
    },
    {
        "id": 13,
        "activity":"Give free music lessons",
        "image": "musicLessons.png",
        "color": "#421FCF",
    },
    {
        "id": 14,
        "activity":"Teach people how to register to vote.",
        "image": "voteRegister.png",
        "color": "#FFBD3E",
    },
    {
        "id": 15,
        "activity":"Clean up your local park",
        "image": "clearnPark.png",
        "color": "#3F90FC",
    },
    {
        "id": 16,
        "activity":"Give IT help to local adults",
        "image": "ITHelp.png",
        "color": "#FF7044",
    },
    {
        "id": 17,
        "activity":"Foster a shelter animal.",
        "image": "animalShelter.png",
        "color": "#FFBD3E",
    },
    {
        "id": 18,
        "activity":"Babysit during PTA meetings.",
        "image": "babySit.png",
        "color": "#3F90FC",
    },
    {
        "id": 19,
        "activity":"Collect stuffed animals.",
        "image": "stuffedAnimals.png",
        "color": "#FF7044",
    },
    {
        "id": 20,
        "activity":"Collect school supplies.",
        "image": "schoolSuffiles.png",
        "color": "#421FCF",
    },
]
export default activity;